### ISSUE TITLE
[FEAT] 멋사 12주차 과제🦁

### ISSUE THREAD

**Issue by OaYenn** [Likelion-at-SMWU-10th/ChoiYeJin#26]
## 📌  Feature Issue

- Django에서 API 만들기

## 📝  To-do

- [ ] 댓글 작성 API
- [ ] 댓글 수정 API
- [ ] 댓글 삭제 API
- [ ] 댓글 조회 API
